twist_mux:
  ros__parameters:
    use_stamped: false
    topics:
      joystick:
        topic: joy_vel
        timeout: 0.5
        priority: 99
      keyboard:
        topic: key_vel
        timeout: 0.5
        priority: 90
      cmd_vel:
        topic: cmd_vel
        timeout: 0.5
        priority: 10