bt_navigator:
  ros__parameters:
    use_sim_time: true
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /humbot_controller/odom
    transform_tolerance: 0.3
    default_server_timeout: 1000
    bt_loop_duration: 10 #every 10ms BT will generate a tick signal
    wait_for_service_timeout: 1000 #each service client waits for 1s for server to respond
    default_nav_to_pose_bt_xml: "/home/ishika/humbot_ws/src/humbot_navigation/behavior_tree/simple_navigation_with_replanning_recovery.xml"
    default_nav_through_poses_bt_xml: "/home/ishika/humbot_ws/src/humbot_navigation/behavior_tree/simple_navigation.xml"
