controller_server:
  ros__parameters:
    use_sim_time: true
    controller_frequency: 20.0 #hz like 20 times/sec
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.001 #radian/sec
    failure_tolerance: 0.3 # seconds, max allowed time for controller to fail
    odom_topic: /humbot_controller/odom
    controller_plugins: ["FollowPath"]
    goal_checker_plugins: ["general_goal_checker"]
    progress_checker_plugin: "progress_checker"

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5 #min amount robot shold move to consider progress
      movement_time_allowance: 10.0 #10s maxamount of time robot has to move using min movement radius
    
    general_goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25 # cm
      yaw_goal_tolerance: 0.25 #radians
      stateful: true

    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      desired_linear_vel: 0.3
      lookahead_dist: 0.6
      min_lookahead_dist: 0.3
      max_lookahead_dist: 0.9
      lookahead_time: 1.5
      rotate_to_heading_angular_vel: 1.8
      transform_tolerance: 0.2
      use_velocity_scaled_lookahead_dist: false
      min_approach_linear_velocity: 0.05
      approach_velocity_scaling_dist: 1.0
      use_collision_detection: true
      max_allowed_time_to_collision_up_to_carrot: 1.0
      use_regulated_linear_velocity_scaling: true
      use_cost_regulated_linear_velocity_scaling: false
      regulated_linear_scaling_min_radius: 0.9
      regulated_linear_scaling_min_speed: 0.25
      use_fixed_curvature_lookahead: false
      curvature_lookahead_dist: 1.0
      use_rotate_to_heading: true
      rotate_to_heading_min_angle: 0.785
      max_angular_accel: 3.2
      max_robot_pose_search_dist: 10.0
      interpolate_curvature_after_goal: false
      cost_scaling_dist: 0.3
      cost_scaling_gain: 1.0
      inflation_cost_scaling_factor: 3.0

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_link
      use_sim_time: true
      robot_radius: 0.1  #0.1m
      resolution: 0.05 #5cm, each cell = 5*5 cm2
      always_send_full_costmap: true
      rolling_window: true
      #local ostmap would be 3x3grid centred in robot and moves along with it
      width: 3 #3m
      height: 3 

      plugins: ["obstacle_layer", "inflation_layer"]
      
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        observation_sources: scan
        scan: 
          topic: /scan
          data_type: "LaserScan" #msg type being published & used to mark obstacle 
          max_obstacle_height: 0.2
          marking: true
          clearing: true #using bresenham line algo to clear the cells where no obstacles are detected
          combination_method: 1 # using the maximum cost among the layers
          raytrace_max_range: 3.0 # 3m
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
      
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.55 #size of inflation around obstacles, should be > robot's footprint
        cost_scaling_factor: 3.0 #way the cost decreases