costmap:
  costmap:   #using it since in humble, there is a namespace for costmap which is costmap and also name of node
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: true
      robot_radius: 0.1  #0.1m
      resolution: 0.05 #5cm, each cell = 5*5 cm2
      always_send_full_costmap: true
      track_unknown_space: true

      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]

      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_topic: "/map"
        map_subscribe_transient_local: true
      
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        observation_sources: scan
        scan: 
          topic: /scan
          data_type: "LaserScan" #msg type being published & used to mark obstacle 
          max_obstacle_height: 0.2
          marking: true
          clearing: true #using bresenham line algo to clear the cells where no obstacles are detected
          combination_method: 1 # using the maximum cost among the layers
          raytrace_max_range: 3.0 # 3m
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
      
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.55 #size of inflation around obstacles, should be > robot's footprint
        cost_scaling_factor: 3.0 #way the cost decreases
        
      




